apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-stats-service-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /userstats.v1.
        pathType: Prefix
        backend:
          service:
            name: user-stats-service
            port:
              number: 80

