image:
  repository: frontend
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: app.gavel.local

# BFF Configuration
# Frontend (BFF) connects to backend services using internal K8s Service DNS
config:
  authServiceUrl: "http://auth-service"
  bidServiceUrl: "http://bid-service"
  userStatsServiceUrl: "http://user-stats-service"
  jwtIssuer: "gavel-auth-service"
  # TODO: this value will be flipped in the prod value chart
  secureCookie: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

replicaCount: 1
